import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./userStyle.css";
import Header from "../../components/Header";
const inter = Inter({ subsets: ["latin"] });
import { Providers } from "../../app/providers";
export const metadata: Metadata = {
  title: "VacaVerse",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />

          {children}
        </Providers>
      </body>
    </html>
  );
}
